default:
  sing-box run -c ./config.json

edit:
  hx ./config.json

update url:
  wget "https://subs.wukaige.com/config/{{url}}&file=https://raw.wukaige.com/sing-box/config.json?token=changeme" -O config.json

