# global config

live_config_reload = true

[env]
TERM = "tmux-256color"
QT_IM_MODULE = "fcitx"

[font]
builtin_box_drawing = true
size = 10.0

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[font.italic]
family = "MesloLGM Nerd Font"
style = "Italic"

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 15
y = 15

[window.position]
x = 0
y = 0


# ###  Themes  ################################################################

[colors.primary]
background = "#111111"
foreground = "#aab2bf"

[colors.normal]
black = "#1e2127"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#ffffff"

