# THIS IS EXPERIMENTAL
# the config file schema may change at any time
style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 26 # column width relative to the terminal window
    min_width: 20 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 42
    min_width: 45
  snippet:
    color: white

finder:
  command: fzf
  overrides: --select-1 --with-nth 1,2,3 --layout reverse
  overrides_var: --no-select-1 --bind=change:unbind(U,D,E,F,G,J,K,L,V,Y)

cheats:
  paths:
    - $HOME/.cheats/
    # - $HOME/.local/share/navi/cheats/
    # - /path/to/another/dir

# search:
  # tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: zsh # shell used for shell out. possible values: bash, zsh, dash, ...
  finder_command: zsh # similar, but for fzf's internals

