# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: cyan
    width_percentage: 15
    min_width: 15
  comment:
    color: blue
    width_percentage: 20
    min_width: 20
  snippet:
    width_percentage: 55
    min_width: 60
    color: white

finder:
  # equivalent to the --finder option
  command: fzf
  # equivalent to the --fzf-overrides option
  overrides: --with-nth='1,2,3' --no-preview
  # equivalent to the --fzf-overrides-var option
  # overrides_var: --tac

# cheats:
#   paths:
#     - /path/to/some/dir # on unix-like os
#     - F:\\path\\to\\dir # on Windows
# path: /path/to/some/dir # (DEPRECATED) equivalent to the --path option

# search:
#   tags: git,!checkout # equivalent to the --tag-rules option

# client:
#   tealdeer: true # enables tealdeer support for navi --tldr

shell:
  # Shell used for shell out. Possible values: bash, zsh, dash, ...
  # For Windows, use `cmd.exe` instead.
  command: zsh

  # finder_command: bash # similar, but for fzf's internals
