#!/usr/bin/env zsh

if [[ $# -eq 0 ]]; then
  selected_dir="$({_zlua -l | sort -g -r} | sed -e '1d' -e 's/~/$HOME/' | fzf)"
  [[ -z "$selected_dir" ]] && return 1 || read _ dir <<< "$selected_dir"
  eval cd $dir
else
  if [[ $# -eq 1 ]] && [[ $(wd $1 | wc -l) -eq 0 ]]; then
    wd $1
  else
    _zlua "$@"
  fi
fi

