- name: Rss
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: full
      widgets:
        - type: split-column
          max-columns: 3
          widgets:
            - type: rss
              title: Qna
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://www.v2ex.com/feed/tab/qna.xml
            - type: rss
              title: Tech
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://www.v2ex.com/feed/tab/tech.xml
            - type: rss
              title: Play
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://www.v2ex.com/feed/tab/play.xml
            - type: rss
              title: Jobs
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://www.v2ex.com/feed/tab/jobs.xml
            - type: rss
              title: Deals
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://www.v2ex.com/feed/tab/deals.xml
            - type: rss
              title: Creative
              limit: 10
              collapse-after: 3
              cache: 12h
              feeds:
                - url: https://www.v2ex.com/feed/tab/creative.xml
