---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Docker & Widget:

    - AdGuard:
        href: http://localhost:8000
        description: Privacy protection center for you and your devices.
        widget:
          type: adguard
          url: http://host.docker.internal:8000
          username: wukaige
          password: changeme

    - Uptime-kuma:
        href: http://localhost:3001
        description: A fancy self-hosted monitoring tool
        widget:
          type: uptimekuma
          url: http://host.docker.internal:3001
          slug: default
          username: wukaige
          password: wit1605121120

    - Grafana:
        href: http://localhost:3000
        description: Grafana is the open source analytics & monitoring solution for every database.
        widget:
          type: grafana
          url: http://host.docker.internal:3000
          username: wukaige
          password: changeme

    - Speed Test:
        href: http://localhost:8082
        description: Runs speedtest checks against Ookla's Speedtest service.
        widget:
          type: speedtest
          url: http://host.docker.internal:8082
          username: wukaigee@gamil.com
          password: changeme

- Docker:

    - IT-TOOLS:
        href: http://localhost:8081
        description: Collection of handy online tools for developers, with great UX.

    - MyIP:
        href: http://localhost:18966
        description: The best IP Toolbox. Easy to check what's your IPs

    - linux-command:
        href: http://localhost:9665
        description: Linux命令大全搜索工具，内容包含Linux命令手册、详解、学习、搜集。

    - Dockge:
        href: http://localhost:5011
        description: A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager

    - planka:
        href: http://localhost:1337
        description: The realtime kanban board for workgroups built with React and Redux.

