---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80

title: Home
# favicon: https://www.google.com/favicon.ico
cardBlur: sm
color: slate
useEqualHeights: false
headerStyle: clean

layout:
  Docker & Widget:
    header: true
    initiallyCollapsed: false

  Docker:
    header: true
    initiallyCollapsed: false

  Developer:
    header: true

  Social:
    header: true

  Entertainment:
    header: true

