#!/usr/bin/env bash

[[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"

if [[ $# -eq 1 ]]; then
  tmux $change -t "$1" &>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1")
else
  if tmux has-session &>/dev/null; then
    session_name="$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0 --select-1)"
    [[ -n "$session_name" ]] && tmux $change -t "$session_name"
  else
    tmux new-session -d -s "$USER" && tmux attach-session -t "$USER"
  fi
fi
