#!/usr/bin/env zsh

if [[ -n "$1" ]]; then
  project="$1"
else
  project=$(tmuxinator list | sed "1d" | xargs -n 1 | while read proj; do
    tmux list-sessions | grep -w "$proj" 1>/dev/null && proj=$proj' - created'
    echo $proj
  done | fzf)
fi
[[ "$project" = *"- created" ]] && echo "project already created." && return
[[ -n "$project" ]] && tmuxinator $project

