
services:
  lobe-chat:
    ports:
      - 3210:3210
    environment:
      - OPENAI_API_KEY=sk-proj-M5eX1vZvLuofvy3FsE9iT3BlbkFJB5qd1muOXupRwaenGWqy
      - OPENAI_PROXY_URL=http://host.docker.internal:7890
      - ACCESS_CODE=lobe66
    container_name: lobe-chat
    image: lobehub/lobe-chat
    extra_hosts:
      - host.docker.internal:host-gateway