$background = rgb(2D2C29)
$foreground = rgb(FCF1E0)
$color0 = rgb(52514E)
$color1 = rgb(616976)
$color2 = rgb(A95622)
$color3 = rgb(987768)
$color4 = rgb(BF801F)
$color5 = rgb(A4A41A)
$color6 = rgb(B8A17C)
$color7 = rgb(F2E2CA)
$color8 = rgb(A99E8D)
$color9 = rgb(818C9E)
$color10 = rgb(E1732E)
$color11 = rgb(CA9F8B)
$color12 = rgb(FFAA29)
$color13 = rgb(DBDA23)
$color14 = rgb(F5D6A6)
$color15 = rgb(F2E2CA)
