#!/usr/bin/env zsh

# Save original IFS and set new one for handling filenames with spaces
original_ifs=$IFS
IFS=$'\n'

git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME status --short | cut -b 2- | grep -v '^ ' | while read -r line; do
  stats=${line:0:1}
  # Trim leading and trailing whitespace and get the file path
  file_path=$(echo ${line:1} | xargs | awk '{print $NF}')
  
  if [[ "$stats" = "D" ]]; then
    # Safely remove the file, checking for errors
    git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME rm -- "${file_path}" || echo "Failed to remove ${file_path}"
  else
    # Safely add the file, checking for errors
    echo "add ${file_path}"
    git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME add -- "${file_path}" || echo "Failed to add ${file_path}"
  fi
done

# Restore original IFS
IFS=$original_ifs

