
services:
  uptime-kuma:
    container_name: uptime-kuma
    environment:
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
    volumes:
      - ~/.docker/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    image: louislam/uptime-kuma:1
    extra_hosts:
      - host.docker.internal:host-gateway
networks: {}
