#!/usr/bin/env zsh

local file_path

# 更改内部字段分隔符为新行，以正确处理带有空格的文件名
IFS=$'\n'
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME status --short | cut -b 2- | grep -v '^ ' | while read -r line; do
  echo "$line"

  stats=${line:0:1}
  file_path=$(echo ${line:1} | xargs | awk '{print $NF}')

  case "$stats" in
    A|M|U) option="add" ;;
    D) option="rm" ;;
    *) echo "unknown status: $stats, file: $file_path" && continue ;;
  esac

  git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME $option -- "${file_path}" | tee

done
unset IFS # 恢复 IFS 到默认值

# autoadd add dir
local dir_path
for dir_path in "${AUTOADD_DIRS[@]}";do
  if [[ -d "$dir_path" ]]; then
    git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME add "${dir_path}"
  else
    echo "autoadd: $dir_path is not a directory."
  fi
done

