#!/usr/bin/env zsh

GITDIR="$HOME/.dotfiles.git"
WORKTREE="$HOME"

# resore staged file
if [[ "$1" = "-s" ]]; then
  git --git-dir=$GITDIR --work-tree=$WORKTREE diff --cached --name-only | while read -r file; do
    echo "restore staged file: $file"
    git --git-dir=$GITDIR --work-tree=$WORKTREE restore --staged $WORKTREE/$file
  done
fi

# resore modified file
git --git-dir=$GITDIR --work-tree=$WORKTREE ls-files -m | while read -r file; do
  info "restore file: $file"
  git --git-dir=$GITDIR --work-tree=$WORKTREE restore -- "$file"
done

