#!/usr/bin/env zsh

if [[ $# -eq 0 ]]; then
  if hash tspin &>/dev/null; then
    cat | tspin
  else
    cat | /usr/bin/tail
  fi
else 
  if hash tspin &>/dev/null; then
    tspin "$@"
  else
    /usr/bin/tail "$@"
  fi
fi
