default:
  color=$(ls ~/.config/alacritty/colors/*.toml | awk -F/ '{gsub(/\.toml$/,"",$NF); print $NF}' | fzf --height 40% --reverse --header="选择 Alacritty 配色") && [ -n "$color" ] && awk -v t="$color" '/^import/{$0="import = [\"~/.config/alacritty/colors/" t ".toml\"]"}1' ~/.config/alacritty/alacritty.toml > tmp && mv tmp ~/.config/alacritty/alacritty.toml && echo "配色已切换至: $color"
