version: "3.3"
services:
  mysql:
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - $HOME/.docker/data/mysql/config:/etc/mysql/conf.d
      - $HOME/.docker/data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    image: mysql:latest
networks: {}
