#!/usr/bin/env zsh

window_name="$(tmux display-message -p '#W')"
pane_nums="$(tmux list-panes | wc -l)"
window_nums="$(tmux list-windows | wc -l)"

[[ "$window_name" = \** ]] && exit 0
[[ $window_nums -eq 1 ]] && [[ $pane_nums -eq 1 ]] && exit 0

tmux kill-pane

