theme = "material_deep_ocean"

[editor]
line-number = "relative"
mouse = false

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 0

[editor.whitespace.render]
space = "none"
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.soft-wrap]
enable = true
max-wrap = 50         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""   # set wrap-indicator to "" to hide it

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-o = ":open ~/.config/helix/config.toml"
C-r = ":config-reload"

# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "insert_mode",
]
S = "surround_add"

# multi cursor
C-v = "copy_selection_on_next_line"

# Clipboards over registers
x = "delete_selection"
s = "change_selection"

# Would be nice to add ya and yi, but the surround commands can't be chained
Y = ["yank_main_selection_to_clipboard", "collapse_selection"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

# Search for word under cursor
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
"#" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]

# Extend and select commands that expect a manual input can't be chained
# I've kept d[X] commands here because it's better to at least have the stuff you want to delete
# selected so that it's just a keystroke away to delete
[keys.normal.d]
d = ["extend_to_line_bounds", "delete_selection"]
t = ["extend_till_char"]
s = ["surround_delete"]
i = ["select_textobject_inner"]
a = ["select_textobject_around"]
j = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_below",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
]
down = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_below",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
]
k = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_above",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
]
up = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_above",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
]
G = [
  "select_mode",
  "extend_to_line_bounds",
  "goto_last_line",
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
]
w = [
  "move_next_word_start",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
W = [
  "move_next_long_word_start",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
g = { g = [
  "select_mode",
  "extend_to_line_bounds",
  "goto_file_start",
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "normal_mode",
] }

[keys.normal.y]
y = ["select_mode", "extend_to_line_bounds", "yank", "collapse_selection"]
j = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_below",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
down = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_below",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
k = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_above",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
up = [
  "select_mode",
  "extend_to_line_bounds",
  "extend_line_above",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
G = [
  "select_mode",
  "extend_to_line_bounds",
  "goto_last_line",
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
w = [
  "move_next_word_start",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
W = [
  "move_next_long_word_start",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
]
g = { g = [
  "select_mode",
  "extend_to_line_bounds",
  "goto_file_start",
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "collapse_selection",
  "normal_mode",
] }

[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]

[keys.insert.j]
k = "normal_mode"

[keys.normal."+"]
m = ":run-shell-command make"
b = ":run-shell-command cargo build"
r = ":run-shell-command cargo run"
t = ":run-shell-command cargo test"

[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"
S = "surround_add"

u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
tab = [
  "insert_mode",
  "collapse_selection",
] # tab is read by most terminal editors as "C-i"
C-a = ["append_mode", "collapse_selection"]

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = ["yank", "delete_selection"]
x = ["yank", "delete_selection"]
y = ["yank", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["yank_main_selection_to_clipboard"]
p = "replace_selections_with_clipboard"                              # No life without this
P = "paste_clipboard_before"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
